services:
  - type: web
    name: gmb-manager
    runtime: node
    region: oregon
    plan: free
    buildCommand: npx prisma generate && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_AUTH_TOKEN
        sync: false
